---
name: Docker build, scan and push on main merge
on:
  push:
    branches:
      - main

env:
  ORG: geekzone
  IMAGE: $ORG/${{ github.repository_name }}
  RUN: ${{ github.run_number }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: $IMAGE:latest
          load: true

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: $IMAGE:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag $IMAGE:latest $IMAGE:$RUN

      - name: Push Docker image
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:$RUN
