---
name: Docker build, scan and push on main merge
on:
  push:
    branches:
      - main

env:
  IMAGE: geekzone/${{ github.event.repository.name }}
  RUN: ${{ github.run_number }}

permissions:
  contents: write


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set version number
        id: version
        run: echo "VERSION_NUMBER=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snyk to check static code for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE }}:latest
          load: true

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE }}:latest
          args: --severity-threshold=medium

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE }}:latest ${{ env.IMAGE }}:${{ env.VERSION_NUMBER }}

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE }}:latest
          docker push ${{ env.IMAGE }}:${{ env.VERSION_NUMBER }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ env.VERSION_NUMBER }}
          name: Release v${{ env.VERSION_NUMBER }}
          draft: false
          prerelease: false
          makeLatest: true
          commit: ${{ github.sha }}
